#!/bin/bash

gcc -w -o keygen keygen.c -std=c99
gcc -w -o otp_enc_d otp_enc_d.c -std=c99
gcc -w -o otp_enc otp_enc.c -std=c99
gcc -w -o otp_dec_d otp_dec_d.c -std=c99
gcc -w -o otp_dec otp_dec.c -std=c99